@startuml packages_short-circuit
set namespaceSeparator none
top to bottom direction
skinparam componentStyle rectangle
rectangle "conftest\n1 python file" as conftest
rectangle "scripts.render_nord_egress_container\n1 python file" as scripts.render_nord_egress_container
rectangle "scripts.render_roaming_policy\n1 python file" as scripts.render_roaming_policy
rectangle "scripts.render_wireguard_access_bundle\n1 python file" as scripts.render_wireguard_access_bundle
rectangle "scripts.render_wireguard_mesh\n1 python file" as scripts.render_wireguard_mesh
@enduml
